# File: Makefile
# ----------------------------
# Build test file with -std=c++11 and debug flag

all:
	g++ -g modelstats.cpp model_unit_tests.cpp modelstats.h -o program
	

run:
	./program

clean:
	rm -f modelapp
